/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/shared/ui/BaseButton.vue')['default']
    BaseButtonArrow: typeof import('./components/shared/ui/BaseButtonArrow.vue')['default']
    BaseButtonCancel: typeof import('./components/shared/ui/BaseButtonCancel.vue')['default']
    BaseButtonIcon: typeof import('./components/shared/ui/BaseButtonIcon.vue')['default']
    BaseButtonIconEdit: typeof import('./components/shared/ui/BaseButtonIconEdit.vue')['default']
    BaseButtonIconShow: typeof import('./components/shared/ui/BaseButtonIconShow.vue')['default']
    BaseButtonRegister: typeof import('./components/shared/ui/BaseButtonRegister.vue')['default']
    BaseButtonSave: typeof import('./components/shared/ui/BaseButtonSave.vue')['default']
    BaseButtonSearch: typeof import('./components/shared/ui/BaseButtonSearch.vue')['default']
    BaseModal: typeof import('./components/shared/modal/BaseModal.vue')['default']
    BasePagination: typeof import('./components/shared/navigation/BasePagination.vue')['default']
    BaseSpinner: typeof import('./components/shared/loaders/BaseSpinner.vue')['default']
    BaseTable: typeof import('./components/shared/data-display/BaseTable.vue')['default']
    FileDrop: typeof import('./components/common/FileDrop.vue')['default']
    Icon: typeof import('./components/common/Icon.vue')['default']
    ImageCropper: typeof import('./components/common/ImageCropper.vue')['default']
    ImageLoader: typeof import('./components/common/ImageLoader.vue')['default']
    LayoutSettings: typeof import('./components/common/LayoutSettings.vue')['default']
    List: typeof import('./components/common/Notifications/List.vue')['default']
    LocaleSelect: typeof import('./components/common/LocaleSelect.vue')['default']
    LocationMap: typeof import('./components/map/LocationMap.vue')['default']
    LtrContext: typeof import('./components/common/LtrContext.vue')['default']
    MapView: typeof import('./components/map/MapView.vue')['default']
    Percentage: typeof import('./components/common/Percentage.vue')['default']
    ProfileSettings: typeof import('./components/profile/ProfileSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./components/common/SearchDialog.vue')['default']
    SegmentedPage: typeof import('./components/common/SegmentedPage.vue')['default']
    TestScope: typeof import('./components/common/TestScope.vue')['default']
    Toolbar: typeof import('./components/common/Notifications/Toolbar.vue')['default']
  }
}
